#!/usr/bin/env python3
"""Pack every CURRENT added PMDCollab behaviour sprite for TamaPoke.

Input: tools/pmd_catalog.json generated by sync_pmd_catalog.py
Output: tools/sdcard/mons/p<ID>.bin + ps<ID>.bin for managed IDs >=810.

Only PMDCollab pixel/behaviour assets are accepted. There is deliberately no
PokeAPI artwork/Showdown/static-image fallback. If a tracker entry turns out to
lack a usable animated behaviour sheet, that TamaPoke entry is disabled and is
listed in tools/pmd_sprite_report.txt instead of becoming an invisible/static
Pokemon. Missing shiny art reuses the NORMAL animated PMD sprite; the normal
sprite itself is never substituted.
"""
from __future__ import annotations
import concurrent.futures as cf
import json, re, shutil, struct, urllib.request, xml.etree.ElementTree as ET
from pathlib import Path
from PIL import Image

HERE=Path(__file__).resolve().parent
ROOT=HERE.parent
CAT=HERE/'pmd_catalog.json'
OUT=HERE/'sdcard'/'mons'
CACHE=HERE/'pmd_cache_catalog'
REPORT=HERE/'pmd_sprite_report.txt'
AUDIT=HERE/'sprite_audit.json'
WEB=HERE/'web_extra'
PREV=WEB/'previews'
RAW='https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/sprite'
UA='TamaPoke-v3.62.8-SingleRelease-BasePackGuard/1.0'
SLOW,MIN_MS,ALPHA_T=1.4,70,128
# Firmware PmdMon::load() accepts at most 3 MiB. Keep generated sprites below
# that hard limit with margin so PUT transfer and PSRAM loading stay reliable.
MAX_TPK_BYTES=2800*1024
ACTIONS=[
 (0,'Idle',0),(1,'Walk',6),(2,'Walk',2),(3,'Sleep',0),
 (4,'Eat',0),(5,'Hurt',0),(6,'Attack',0),(7,'Pose',0),
 (8,'Hop',0),(9,'Nod',0),(10,'DeepBreath',0),(11,'Sit',0),
]

def fetch(rel:str,dest:Path)->Path:
    if dest.is_file() and dest.stat().st_size>0:return dest
    dest.parent.mkdir(parents=True,exist_ok=True)
    req=urllib.request.Request(f'{RAW}/{rel}',headers={'User-Agent':UA})
    with urllib.request.urlopen(req,timeout=75) as r:data=r.read()
    if not data:raise RuntimeError('empty HTTP body')
    dest.write_bytes(data);return dest

def rgb565(r,g,b):return (r>>3)<<11 | (g>>2)<<5 | (b>>3)

def load_animdata(xml_path:Path):
    root=ET.parse(xml_path).getroot(); ar=root.find('Anims')
    if ar is None:raise RuntimeError('AnimData.xml has no <Anims>')
    raw={}
    for a in ar:
        ne=a.find('Name')
        if ne is None or not ne.text:continue
        name=ne.text
        cp=a.find('CopyOf'); fw=a.find('FrameWidth'); fh=a.find('FrameHeight'); ds=a.find('Durations')
        if fw is None:
            raw[name]=('copy',cp.text) if cp is not None and cp.text else None;continue
        if fh is None or ds is None:continue
        d=[int(x.text) for x in ds if x.text]
        raw[name]=(int(fw.text),int(fh.text),d,name)
    def resolve(name,seen=None):
        seen=set() if seen is None else seen
        if name in seen:return None
        seen.add(name); v=raw.get(name)
        if isinstance(v,tuple) and v and v[0]=='copy':return resolve(v[1],seen)
        return v
    return {k:resolve(k) for k in raw}

def _frame_indices(total:int, cap:int):
    """Evenly sample up to cap frames while preserving first/last motion."""
    if total <= cap: return list(range(total))
    if cap <= 1: return [0]
    out=[]
    for j in range(cap):
        i=round(j*(total-1)/(cap-1))
        if not out or i!=out[-1]: out.append(i)
    return out

def _pack_profile(relroot:str,outpath:Path,anims,selected,max_frames:int):
    safe=relroot.replace('/','_'); folder=CACHE/safe
    colmap={}; pal=[]; packed=[]; used=[]
    for aid,name,row,(fw,fh,durs,src) in selected:
        png=folder/f'{src}-Anim.png'; fetch(f'{relroot}/{src}-Anim.png',png)
        im=Image.open(png).convert('RGBA')
        rows=max(1,im.height//fh); rr=row if row<rows else 0
        source_nf=min(len(durs),im.width//fw,24)
        if source_nf<=0:continue
        idxs=_frame_indices(source_nf,min(max_frames,source_nf))

        # v3.61.2 stability: crop the union of visible pixels across the sampled
        # action frames BEFORE indexing. PMDCollab sheets often reserve very large
        # transparent canvases. Keeping those margins bloated TPK2/3, made PmdMon
        # scan millions of empty pixels on load and forced the renderer to walk
        # them every frame. The TamaPoke renderer already centers the visible body
        # and anchors at the lowest visible row, so an action-wide crop preserves
        # the on-screen pose while dramatically reducing work.
        frames=[]; bbox=None
        for i in idxs:
            fr=im.crop((i*fw,rr*fh,(i+1)*fw,(rr+1)*fh))
            alpha=fr.getchannel('A').point(lambda a: 255 if a>=ALPHA_T else 0)
            b=alpha.getbbox()
            if b:
                bbox=b if bbox is None else (
                    min(bbox[0],b[0]), min(bbox[1],b[1]),
                    max(bbox[2],b[2]), max(bbox[3],b[3]))
            frames.append(fr)
        if bbox is None: continue
        # One transparent pixel of breathing room avoids edge-clipping outlines.
        l=max(0,bbox[0]-1); t=max(0,bbox[1]-1)
        r=min(fw,bbox[2]+1); b=min(fh,bbox[3]+1)
        cw,ch=r-l,b-t
        if cw<=0 or ch<=0: continue

        data=bytearray(); ms=[]; frame_boxes=[]
        for pos,(i,fr) in enumerate(zip(idxs,frames)):
            fr=fr.crop((l,t,r,b))
            alpha=fr.getchannel('A').point(lambda a: 255 if a>=ALPHA_T else 0)
            fb=alpha.getbbox()
            if fb is None: fb=(0,0,cw,ch)
            fl,ft,fright,fbottom=fb
            # One-byte exact frame bounds are stored in TPK3. The firmware uses
            # them to skip transparent margins without scanning the whole file
            # when the Pokemon is loaded from SD.
            frame_boxes.append((fl,ft,fright,fbottom))
            for px in fr.getdata():
                if px[3]<ALPHA_T:data.append(0xFF);continue
                key=px[:3]
                if key not in colmap:
                    if len(pal)>=255:
                        nearest=min(colmap,key=lambda c:sum((a-b)**2 for a,b in zip(c,key)))
                        colmap[key]=colmap[nearest]
                    else:colmap[key]=len(pal);pal.append(key)
                data.append(colmap[key])
            ms.append(max(MIN_MS,round(durs[i]*1000/60*SLOW)))
        nf=len(idxs)
        packed.append((aid,cw,ch,nf,frame_boxes,ms,bytes(data)))
        crop_note=f'{fw}x{fh}->{cw}x{ch}' if (cw!=fw or ch!=fh) else f'{fw}x{fh}'
        used.append(f'{aid}:{name}:{nf}f@{crop_note}')
    ids={x[0] for x in packed}
    if 0 not in ids or 1 not in ids:raise RuntimeError('animated Idle/Walk vanished while packing')
    outpath.parent.mkdir(parents=True,exist_ok=True)
    with outpath.open('wb') as f:
        # TPK3 is TPK2 plus 4 bytes (L,T,R,B) per frame before its duration.
        # The v3.61.6 firmware remains backward-compatible with all original TPK2
        # region packs, while current catalog sprites load without a pixel scan.
        f.write(b'TPK3');f.write(struct.pack('<BH',len(packed),len(pal)))
        for r,g,b in pal:f.write(struct.pack('<H',rgb565(r,g,b)))
        for aid,fw,fh,nf,boxes,ms,data in packed:
            if fw>255 or fh>255:raise RuntimeError(f'PMD frame too large for TPK3: {fw}x{fh}')
            f.write(struct.pack('<4B',aid,fw,fh,nf))
            for box in boxes:f.write(struct.pack('<4B',*box))
            f.write(struct.pack(f'<{nf}H',*ms));f.write(data)
    if outpath.stat().st_size<64:raise RuntimeError('TPK3 unexpectedly small')
    return ', '.join(used)

def pack_one(out_id:int,relroot:str,outpath:Path):
    safe=relroot.replace('/','_'); folder=CACHE/safe
    xml=fetch(f'{relroot}/AnimData.xml',folder/'AnimData.xml')
    anims=load_animdata(xml)
    # Choose a genuine PMD multi-frame action as fallback for incomplete entries.
    mover=None
    for pref in ('Idle','Walk','Pose','Hop','Attack','Hurt','Sleep'):
        v=anims.get(pref)
        if v and len(v[2])>=2:mover=(pref,v);break
    if mover is None:
        for n,v in anims.items():
            if v and len(v[2])>=2:mover=(n,v);break
    if mover is None:raise RuntimeError('no multi-frame PMDCollab behavior animation')

    selected=[]
    for aid,name,row in ACTIONS:
        v=anims.get(name)
        if (aid in (0,1,2)) and (v is None or len(v[2])<2):
            name,v=mover
        if not v or not v[2]:continue
        selected.append((aid,name,row,v))
    if not any(x[0]==0 for x in selected) or not any(x[0]==1 for x in selected):
        raise RuntimeError('could not map animated Idle/Walk')

    # First preserve the full PMDCollab action set. Oversized community sheets can
    # exceed both the 4 MiB USB PUT guard and, more importantly, the firmware's
    # 3 MiB PmdMon loader limit. Retry progressively smaller *animated* profiles;
    # never replace them with static art.
    profiles=[
        ({0,1,2,3,4,5,6,7,8,9,10,11},24,'full'),
        ({0,1,2,3,4,5,6,7,8,9,10,11},12,'all-actions/12f'),
        ({0,1,2,3,4,5,6,7},12,'core+eat+pose/12f'),
        ({0,1,2,3,5,6,7},10,'core+pose/10f'),
        ({0,1,2,3,5,6},8,'core/8f'),
        ({0,1,2,5,6},6,'compact/6f'),
        ({0,1,2,5,6},4,'compact/4f'),
    ]
    tried=[]
    for allowed,frame_cap,label in profiles:
        subset=[x for x in selected if x[0] in allowed]
        used=_pack_profile(relroot,outpath,anims,subset,frame_cap)
        size=outpath.stat().st_size
        tried.append(f'{label}={size}')
        if size <= MAX_TPK_BYTES:
            note='' if label=='full' else f' [size-optimized:{label}; {size//1024}KiB]'
            return used+note
    outpath.unlink(missing_ok=True)
    raise RuntimeError('animated TPK3 still exceeds safe 2.8 MiB after compaction: '+', '.join(tried))

def patch_enabled(catalog):
    enabled_by_id={int(e['id']):1 if e.get('enabled') else 0 for e in catalog['entries'] if int(e['id'])>=810}
    p=ROOT/'dex.h';s=p.read_text(encoding='utf-8')
    m=re.search(r'(static const uint8_t DEX_ENABLED\[DEX_COUNT \+ 1\] = \{\n)(.*?)(\n\};)',s,re.S)
    if not m:return
    vals=[int(x) for x in re.findall(r'\b[01]\b',m.group(2))]
    for i,v in enabled_by_id.items():
        if 0<=i<len(vals):vals[i]=v
    body='\n'.join('  '+', '.join(str(x) for x in vals[i:i+64])+',' for i in range(0,len(vals),64))
    p.write_text(s[:m.start()]+m.group(1)+body+m.group(3)+s[m.end():],encoding='utf-8')

def make_preview(relroot:str,outpath:Path):
    """Save one cropped pixel-perfect Idle frame from the exact PMD source used for TPK3."""
    safe=relroot.replace('/','_'); folder=CACHE/safe
    xml=fetch(f'{relroot}/AnimData.xml',folder/'AnimData.xml')
    anims=load_animdata(xml)
    pick=None
    for pref in ('Idle','Walk','Pose','Attack','Hurt'):
        v=anims.get(pref)
        if v and v[2]: pick=v; break
    if not pick:
        pick=next((v for v in anims.values() if v and v[2]),None)
    if not pick: raise RuntimeError('preview animation unavailable')
    fw,fh,durs,src=pick
    png=folder/f'{src}-Anim.png'; fetch(f'{relroot}/{src}-Anim.png',png)
    im=Image.open(png).convert('RGBA')
    fr=im.crop((0,0,min(fw,im.width),min(fh,im.height)))
    alpha=fr.getchannel('A').point(lambda a:255 if a>=ALPHA_T else 0)
    box=alpha.getbbox()
    if box: fr=fr.crop(box)
    outpath.parent.mkdir(parents=True,exist_ok=True)
    fr.save(outpath,optimize=True)

def worker(e):
    iid=int(e['id']); name=e.get('name',str(iid)); rel=e.get('pmd_path')
    if not e.get('enabled') or not rel:return iid,False,f'SKIP {iid} {name}: tracker has no behavior sprite'
    normal=OUT/f'p{iid:03d}.bin'; shiny=OUT/f'ps{iid:03d}.bin'
    normal.unlink(missing_ok=True);shiny.unlink(missing_ok=True)
    try:
        used=pack_one(iid,rel,normal)
        make_preview(rel,PREV/f'p{iid:03d}.png')
    except Exception as ex:
        return iid,False,f'MISSING {iid} {name} [{rel}]: {ex}'
    shiny_note='same animated normal (no separate shiny behavior sprite)'
    sr=e.get('shiny_path')
    if sr:
        try:
            pack_one(iid,sr,shiny);shiny_note=f'PMDCollab shiny [{sr}]'
        except Exception as ex:
            shutil.copy2(normal,shiny);shiny_note=f'normal animation reused; shiny failed: {ex}'
    else:shutil.copy2(normal,shiny)
    return iid,True,f'OK {iid} {name} [{rel}] | {used} | shiny: {shiny_note}'

def main():
    cat=json.loads(CAT.read_text(encoding='utf-8'))
    OUT.mkdir(parents=True,exist_ok=True)
    PREV.mkdir(parents=True,exist_ok=True)
    managed=[e for e in cat['entries'] if int(e['id'])>=810]
    lines=['TamaPoke v3.62.8 PMDCollab behavior-sprite pack report + previews',f"Source: {cat.get('source')}",
           'Policy: real PMDCollab animated pixel assets only; approved Mega36 only; no G-Max/static-art fallback','']
    results=[]
    with cf.ThreadPoolExecutor(max_workers=12) as ex:
        for r in ex.map(worker,managed):results.append(r);print(r[2],flush=True)
    byid={i:(ok,msg) for i,ok,msg in results}
    for e in cat['entries']:
        i=int(e['id'])
        if i in byid:
            ok,msg=byid[i];e['enabled']=bool(ok);e['sprite_status']=msg
    lines += [x[2] for x in sorted(results)]
    okn=sum(1 for _,ok,_ in results if ok); miss=sum(1 for _,ok,_ in results if not ok)
    lines += ['',f'PACKED ADDED ENTRIES: {okn}',f'DISABLED/MISSING: {miss}']
    REPORT.write_text('\n'.join(lines)+'\n',encoding='utf-8')
    CAT.write_text(json.dumps(cat,ensure_ascii=False,indent=2),encoding='utf-8')
    if AUDIT.is_file():
        audit=json.loads(AUDIT.read_text(encoding='utf-8'))
        byid_a={int(x['id']):x for x in audit.get('entries',[])}
        for e in cat['entries']:
            iid=int(e['id']); a=byid_a.get(iid)
            if not a: continue
            prev=PREV/f'p{iid:03d}.png'
            a['enabled']=bool(e.get('enabled'))
            a['local_preview']=f'previews/p{iid:03d}.png' if prev.is_file() else None
            e['preview']=a['local_preview']
        AUDIT.write_text(json.dumps(audit,ensure_ascii=False,indent=2),encoding='utf-8')
        CAT.write_text(json.dumps(cat,ensure_ascii=False,indent=2),encoding='utf-8')
    patch_enabled(cat)
    if okn==0:raise SystemExit('No current added PMDCollab sprites could be packed')
    print(f'Packed {okn} added species/forms; {miss} unavailable entries were safely disabled.')

if __name__=='__main__':main()
